trigger:
  - main # Replace with your branch name

pr:
  - '*'

pool:
  vmImage: 'windows-latest'

steps:
  - script: dotnet restore
    displayName: 'Restore .NET Packages'

  - script: dotnet build --configuration Release
    displayName: 'Build .NET Application'

  - script: dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
    displayName: 'Publish .NET Application'

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: true
      projects: '**/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

# Add deployment steps here
