# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main  # Replace with the branch you want to trigger the pipeline on

pr:
- '*'

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    installationPath: $(Agent.ToolsDirectory)/dotnet
    installationPathSelection: 'version'

- script: dotnet build --configuration $(BuildConfiguration)
  displayName: 'Build the project'

- script: dotnet publish --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish
  displayName: 'Publish the project'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/artifacts.zip'
    replaceExistingArchive: true
